//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rehber.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Iletisim
    {
        public int Id { get; set; }
        public int RehberId { get; set; }
        public byte IletisimTuru { get; set; }
        public string IAciklama { get; set; }
    
        public virtual RehberInfo RehberInfo { get; set; }
    }
}
