//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rehber.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Lokasyon
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Lokasyon()
        {
            this.RehberInfo = new HashSet<RehberInfo>();
        }
    
        public int Id { get; set; }
        public Nullable<int> ParentId { get; set; }
        public string LAciklama { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RehberInfo> RehberInfo { get; set; }
    }
}
