//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rehber.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class RehberInfo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public RehberInfo()
        {
            this.Iletisim = new HashSet<Iletisim>();
        }
    
        public int Id { get; set; }
        public byte RehberKayitTuru { get; set; }
        public string Ad { get; set; }
        public string Soyad { get; set; }
        public string DepartmanAdi { get; set; }
        public string Sirket { get; set; }
        public string SirketUnvani { get; set; }
        public string BirimAdi { get; set; }
        public string Gorevi { get; set; }
        public string Santiye { get; set; }
        public string RAciklama { get; set; }
        public int LokasId { get; set; }
        public string Yetkilisi { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Iletisim> Iletisim { get; set; }
        public virtual Lokasyon Lokasyon { get; set; }
    }
}
